# Generated by Django 4.2.4 on 2023-09-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitormanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
