# Generated by Django 4.2.4 on 2023-09-06 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectTaskManagement', '0004_remove_task_hello_remove_task_assignedto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='task',
            name='assignedTo',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
