# Generated by Django 4.2.4 on 2023-09-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectTaskManagement', '0003_alter_project_name'),
        ('projectTaskManagement', '0005_remove_task_assignedto_task_assignedto'),
    ]

    operations = [
    ]
